"""
individual_options = [\

]

all_xml2 = [\

]

all_expat = [\

]

all_xerces = [\

]

all_no_packages = [\

]

all_with_packages = [\

]

all_combinations = [\

]

"""

faster_scan_xml2 = [\
['packages', 'xml2', 'check', 'examples'],
['packages', 'xml2', 'check', 'strict', 'examples'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['packages', 'xml2', 'check', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'examples', 'python'],
['packages', 'xml2', 'check', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'examples', 'perl'],
['packages', 'xml2', 'check', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'examples', 'r'],
['packages', 'xml2', 'check', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'examples', 'ruby']]


faster_scan_expat = [\
['packages', 'expat', 'check', 'examples'],
['packages', 'expat', 'check', 'strict', 'examples'],
['packages', 'expat', 'check', 'cpp_ns', 'examples'],
['packages', 'expat', 'check', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'examples', 'python'],
['packages', 'expat', 'check', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'examples', 'perl'],
['packages', 'expat', 'check', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'examples', 'csharp'],
['packages', 'expat', 'check', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'examples', 'r'],
['packages', 'expat', 'check', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'examples', 'ruby']]

faster_scan_xerces = [\
['packages', 'xerces', 'check', 'strict', 'examples'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['packages', 'xerces', 'check', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'examples', 'python'],
['packages', 'xerces', 'check', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'examples', 'perl'],
['packages', 'xerces', 'check', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'examples', 'r'],
['packages', 'xerces', 'check', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'examples', 'ruby']]

fast_scan_xerces = [\
['xerces', 'check', 'examples'],
['xerces', 'check', 'strict', 'examples'],
['xerces', 'check', 'cpp_ns', 'examples'],
['xerces', 'check', 'python'],
['xerces', 'check', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'python'],
['xerces', 'check', 'perl'],
['xerces', 'check', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'perl'],
['xerces', 'check', 'csharp'],
['xerces', 'check', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'csharp'],
['xerces', 'check', 'r'],
['xerces', 'check', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'r'],
['xerces', 'check', 'ruby'],
['xerces', 'check', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'ruby'],
['packages', 'xerces', 'check', 'examples'],
['packages', 'xerces', 'check', 'strict', 'examples'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['packages', 'xerces', 'check', 'python'],
['packages', 'xerces', 'check', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'python'],
['packages', 'xerces', 'check', 'perl'],
['packages', 'xerces', 'check', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['packages', 'xerces', 'check', 'csharp'],
['packages', 'xerces', 'check', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['packages', 'xerces', 'check', 'r'],
['packages', 'xerces', 'check', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'r'],
['packages', 'xerces', 'check', 'ruby'],
['packages', 'xerces', 'check', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'ruby']]

fast_scan_r = [\
['packages', 'xml2', 'check', 'examples'],
['packages', 'expat', 'check', 'examples'],
['packages', 'xerces', 'check', 'examples'],
['packages', 'xml2', 'check', 'examples', 'r'],
['packages', 'expat', 'check', 'examples', 'r'],
['packages', 'xerces', 'check', 'examples', 'r'],
['packages', 'xml2', 'check', 'strict', 'examples', 'r'],
['packages', 'expat', 'check', 'strict', 'examples', 'r'],
['packages', 'xerces', 'check', 'strict', 'examples', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r']]

faster_scan = [\
['packages', 'xml2', 'check', 'examples'],
['packages', 'expat', 'check', 'examples'],
['packages', 'xerces', 'check', 'examples'],
['packages', 'xml2', 'check', 'strict', 'examples'],
['packages', 'expat', 'check', 'strict', 'examples'],
['packages', 'xerces', 'check', 'strict', 'examples'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['packages', 'expat', 'check', 'cpp_ns', 'examples'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['packages', 'xml2', 'check', 'python'],
['packages', 'expat', 'check', 'python'],
['packages', 'xerces', 'check', 'python'],
['packages', 'xml2', 'check', 'strict', 'python'],
['packages', 'expat', 'check', 'strict', 'python'],
['packages', 'xerces', 'check', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'python'],
['packages', 'xml2', 'check', 'perl'],
['packages', 'expat', 'check', 'perl'],
['packages', 'xerces', 'check', 'perl'],
['packages', 'xml2', 'check', 'strict', 'perl'],
['packages', 'expat', 'check', 'strict', 'perl'],
['packages', 'xerces', 'check', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['packages', 'xml2', 'check', 'csharp'],
['packages', 'expat', 'check', 'csharp'],
['packages', 'xerces', 'check', 'csharp'],
['packages', 'xml2', 'check', 'strict', 'csharp'],
['packages', 'expat', 'check', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['packages', 'xml2', 'check', 'r'],
['packages', 'expat', 'check', 'r'],
['packages', 'xerces', 'check', 'r'],
['packages', 'xml2', 'check', 'strict', 'r'],
['packages', 'expat', 'check', 'strict', 'r'],
['packages', 'xerces', 'check', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'r'],
['packages', 'xml2', 'check', 'ruby'],
['packages', 'expat', 'check', 'ruby'],
['packages', 'xerces', 'check', 'ruby'],
['packages', 'xml2', 'check', 'strict', 'ruby'],
['packages', 'expat', 'check', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'ruby']]

fast_scan = [\
['packages', 'xml2', 'check', 'examples'],
['packages', 'expat', 'check', 'examples'],
['packages', 'xerces', 'check', 'examples'],
['packages', 'xml2', 'check', 'strict', 'examples'],
['packages', 'expat', 'check', 'strict', 'examples'],
['packages', 'xerces', 'check', 'strict', 'examples'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['packages', 'expat', 'check', 'cpp_ns', 'examples'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['packages', 'xml2', 'check', 'examples', 'python'],
['packages', 'expat', 'check', 'examples', 'python'],
['packages', 'xerces', 'check', 'examples', 'python'],
['packages', 'xml2', 'check', 'strict', 'examples', 'python'],
['packages', 'expat', 'check', 'strict', 'examples', 'python'],
['packages', 'xerces', 'check', 'strict', 'examples', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xml2', 'check', 'examples', 'perl'],
['packages', 'expat', 'check', 'examples', 'perl'],
['packages', 'xerces', 'check', 'examples', 'perl'],
['packages', 'xml2', 'check', 'strict', 'examples', 'perl'],
['packages', 'expat', 'check', 'strict', 'examples', 'perl'],
['packages', 'xerces', 'check', 'strict', 'examples', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xml2', 'check', 'examples', 'csharp'],
['packages', 'expat', 'check', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'strict', 'examples', 'csharp'],
['packages', 'expat', 'check', 'strict', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'strict', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'r'],
['packages', 'expat', 'check', 'examples', 'r'],
['packages', 'xerces', 'check', 'examples', 'r'],
['packages', 'xml2', 'check', 'strict', 'examples', 'r'],
['packages', 'expat', 'check', 'strict', 'examples', 'r'],
['packages', 'xerces', 'check', 'strict', 'examples', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xml2', 'check', 'examples', 'ruby'],
['packages', 'expat', 'check', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'strict', 'examples', 'ruby'],
['packages', 'expat', 'check', 'strict', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'strict', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'ruby']]

ind_bindings = [['check', 'csharp'], ['check', 'java'], ['check', 'perl'],\
                ['check', 'python'], ['check', 'r'], ['check', 'ruby']]

ind_bindings_packages = [['check', 'packages', 'csharp'], ['check', 'packages', 'java'],\
    ['check', 'packages', 'perl'], ['check', 'packages', 'python'], ['check', 'packages', 'r'],\
    ['check', 'packages', 'ruby']]

ind_opts = [\
['check', 'csharp'], ['check', 'java'], ['check', 'perl'],  ['check', 'python'], ['check', 'r'], ['check', 'ruby'],\
['check', 'packages'], ['check', 'examples'], ['check', 'strict'], ['check', 'cpp_ns'], \
['check', 'expat'], ['check', 'xerces']]

xml2_packages = [\
['packages', 'xml2', 'check', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns'],
['packages', 'xml2', 'check', 'examples', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'xml2', 'check', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'java'],
['packages', 'xml2', 'check', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'java'],
['packages', 'xml2', 'check', 'examples', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'xml2', 'check', 'examples', 'perl'],
['packages', 'xml2', 'check', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'perl'],
['packages', 'xml2', 'check', 'examples', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'xml2', 'check', 'examples', 'python'],
['packages', 'xml2', 'check', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'python'],
['packages', 'xml2', 'check', 'examples', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'xml2', 'check', 'examples', 'r'],
['packages', 'xml2', 'check', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'r'],
['packages', 'xml2', 'check', 'examples', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'xml2', 'check', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'ruby'],
['packages', 'xml2', 'check', 'examples', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]

expat_packages = [\
['packages', 'expat', 'check', 'examples'],
['packages', 'expat', 'check', 'strict'],
['packages', 'expat', 'check', 'cpp_ns'],
['packages', 'expat', 'check', 'examples', 'strict'],
['packages', 'expat', 'check', 'cpp_ns', 'examples'],
['packages', 'expat', 'check', 'cpp_ns', 'strict'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'expat', 'check', 'examples', 'csharp'],
['packages', 'expat', 'check', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'csharp'],
['packages', 'expat', 'check', 'examples', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'expat', 'check', 'examples', 'java'],
['packages', 'expat', 'check', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'java'],
['packages', 'expat', 'check', 'examples', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'expat', 'check', 'examples', 'perl'],
['packages', 'expat', 'check', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'perl'],
['packages', 'expat', 'check', 'examples', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'expat', 'check', 'examples', 'python'],
['packages', 'expat', 'check', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'python'],
['packages', 'expat', 'check', 'examples', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'expat', 'check', 'examples', 'r'],
['packages', 'expat', 'check', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'r'],
['packages', 'expat', 'check', 'examples', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'expat', 'check', 'examples', 'ruby'],
['packages', 'expat', 'check', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'ruby'],
['packages', 'expat', 'check', 'examples', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]

xerces_packages = [\
['packages', 'xerces', 'check', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns'],
['packages', 'xerces', 'check', 'examples', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'xerces', 'check', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'java'],
['packages', 'xerces', 'check', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'java'],
['packages', 'xerces', 'check', 'examples', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'xerces', 'check', 'examples', 'perl'],
['packages', 'xerces', 'check', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['packages', 'xerces', 'check', 'examples', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'xerces', 'check', 'examples', 'python'],
['packages', 'xerces', 'check', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'python'],
['packages', 'xerces', 'check', 'examples', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'xerces', 'check', 'examples', 'r'],
['packages', 'xerces', 'check', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'r'],
['packages', 'xerces', 'check', 'examples', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'xerces', 'check', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'ruby'],
['packages', 'xerces', 'check', 'examples', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]

all_xml2 = [\
['xml2', 'check', 'examples'],
['xml2', 'check', 'strict'],
['xml2', 'check', 'cpp_ns'],
['xml2', 'check', 'examples', 'strict'],
['xml2', 'check', 'cpp_ns', 'examples'],
['xml2', 'check', 'cpp_ns', 'strict'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['xml2', 'check', 'examples', 'csharp'],
['xml2', 'check', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'csharp'],
['xml2', 'check', 'examples', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['xml2', 'check', 'examples', 'java'],
['xml2', 'check', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'java'],
['xml2', 'check', 'examples', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'examples', 'java'],
['xml2', 'check', 'cpp_ns', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['xml2', 'check', 'examples', 'perl'],
['xml2', 'check', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'perl'],
['xml2', 'check', 'examples', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['xml2', 'check', 'examples', 'python'],
['xml2', 'check', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'python'],
['xml2', 'check', 'examples', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'examples', 'python'],
['xml2', 'check', 'cpp_ns', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['xml2', 'check', 'examples', 'r'],
['xml2', 'check', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'r'],
['xml2', 'check', 'examples', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'examples', 'r'],
['xml2', 'check', 'cpp_ns', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['xml2', 'check', 'examples', 'ruby'],
['xml2', 'check', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'ruby'],
['xml2', 'check', 'examples', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'examples', 'ruby'],
['xml2', 'check', 'cpp_ns', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'examples'],
['packages', 'xml2', 'check', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns'],
['packages', 'xml2', 'check', 'examples', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'xml2', 'check', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'java'],
['packages', 'xml2', 'check', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'java'],
['packages', 'xml2', 'check', 'examples', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'xml2', 'check', 'examples', 'perl'],
['packages', 'xml2', 'check', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'perl'],
['packages', 'xml2', 'check', 'examples', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'xml2', 'check', 'examples', 'python'],
['packages', 'xml2', 'check', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'python'],
['packages', 'xml2', 'check', 'examples', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'xml2', 'check', 'examples', 'r'],
['packages', 'xml2', 'check', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'r'],
['packages', 'xml2', 'check', 'examples', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'xml2', 'check', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'ruby'],
['packages', 'xml2', 'check', 'examples', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]

all_expat = [\
['expat', 'check', 'examples'],
['expat', 'check', 'strict'],
['expat', 'check', 'cpp_ns'],
['expat', 'check', 'examples', 'strict'],
['expat', 'check', 'cpp_ns', 'examples'],
['expat', 'check', 'cpp_ns', 'strict'],
['expat', 'check', 'cpp_ns', 'examples', 'strict'],
['expat', 'check', 'examples', 'csharp'],
['expat', 'check', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'csharp'],
['expat', 'check', 'examples', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['expat', 'check', 'examples', 'java'],
['expat', 'check', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'java'],
['expat', 'check', 'examples', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'examples', 'java'],
['expat', 'check', 'cpp_ns', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['expat', 'check', 'examples', 'perl'],
['expat', 'check', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'perl'],
['expat', 'check', 'examples', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'examples', 'perl'],
['expat', 'check', 'cpp_ns', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['expat', 'check', 'examples', 'python'],
['expat', 'check', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'python'],
['expat', 'check', 'examples', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'examples', 'python'],
['expat', 'check', 'cpp_ns', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['expat', 'check', 'examples', 'r'],
['expat', 'check', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'r'],
['expat', 'check', 'examples', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'examples', 'r'],
['expat', 'check', 'cpp_ns', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['expat', 'check', 'examples', 'ruby'],
['expat', 'check', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'ruby'],
['expat', 'check', 'examples', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'examples', 'ruby'],
['expat', 'check', 'cpp_ns', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['packages', 'expat', 'check', 'examples'],
['packages', 'expat', 'check', 'strict'],
['packages', 'expat', 'check', 'cpp_ns'],
['packages', 'expat', 'check', 'examples', 'strict'],
['packages', 'expat', 'check', 'cpp_ns', 'examples'],
['packages', 'expat', 'check', 'cpp_ns', 'strict'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'expat', 'check', 'examples', 'csharp'],
['packages', 'expat', 'check', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'csharp'],
['packages', 'expat', 'check', 'examples', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'expat', 'check', 'examples', 'java'],
['packages', 'expat', 'check', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'java'],
['packages', 'expat', 'check', 'examples', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'expat', 'check', 'examples', 'perl'],
['packages', 'expat', 'check', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'perl'],
['packages', 'expat', 'check', 'examples', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'expat', 'check', 'examples', 'python'],
['packages', 'expat', 'check', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'python'],
['packages', 'expat', 'check', 'examples', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'expat', 'check', 'examples', 'r'],
['packages', 'expat', 'check', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'r'],
['packages', 'expat', 'check', 'examples', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'expat', 'check', 'examples', 'ruby'],
['packages', 'expat', 'check', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'ruby'],
['packages', 'expat', 'check', 'examples', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]

all_xerces = [\
['xerces', 'check', 'examples'],
['xerces', 'check', 'strict'],
['xerces', 'check', 'cpp_ns'],
['xerces', 'check', 'examples', 'strict'],
['xerces', 'check', 'cpp_ns', 'examples'],
['xerces', 'check', 'cpp_ns', 'strict'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['xerces', 'check', 'examples', 'csharp'],
['xerces', 'check', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'csharp'],
['xerces', 'check', 'examples', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['xerces', 'check', 'examples', 'java'],
['xerces', 'check', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'java'],
['xerces', 'check', 'examples', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'examples', 'java'],
['xerces', 'check', 'cpp_ns', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['xerces', 'check', 'examples', 'perl'],
['xerces', 'check', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'perl'],
['xerces', 'check', 'examples', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['xerces', 'check', 'examples', 'python'],
['xerces', 'check', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'python'],
['xerces', 'check', 'examples', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'examples', 'python'],
['xerces', 'check', 'cpp_ns', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['xerces', 'check', 'examples', 'r'],
['xerces', 'check', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'r'],
['xerces', 'check', 'examples', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'examples', 'r'],
['xerces', 'check', 'cpp_ns', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['xerces', 'check', 'examples', 'ruby'],
['xerces', 'check', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'ruby'],
['xerces', 'check', 'examples', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'examples', 'ruby'],
['xerces', 'check', 'cpp_ns', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'examples'],
['packages', 'xerces', 'check', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns'],
['packages', 'xerces', 'check', 'examples', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'xerces', 'check', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'java'],
['packages', 'xerces', 'check', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'java'],
['packages', 'xerces', 'check', 'examples', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'xerces', 'check', 'examples', 'perl'],
['packages', 'xerces', 'check', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['packages', 'xerces', 'check', 'examples', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'xerces', 'check', 'examples', 'python'],
['packages', 'xerces', 'check', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'python'],
['packages', 'xerces', 'check', 'examples', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'xerces', 'check', 'examples', 'r'],
['packages', 'xerces', 'check', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'r'],
['packages', 'xerces', 'check', 'examples', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'xerces', 'check', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'ruby'],
['packages', 'xerces', 'check', 'examples', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]

all_no_packages = [\
['xml2', 'check', 'examples'],
['xml2', 'check', 'strict'],
['xml2', 'check', 'cpp_ns'],
['xml2', 'check', 'examples', 'strict'],
['xml2', 'check', 'cpp_ns', 'examples'],
['xml2', 'check', 'cpp_ns', 'strict'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['xml2', 'check', 'examples', 'csharp'],
['xml2', 'check', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'csharp'],
['xml2', 'check', 'examples', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['xml2', 'check', 'examples', 'java'],
['xml2', 'check', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'java'],
['xml2', 'check', 'examples', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'examples', 'java'],
['xml2', 'check', 'cpp_ns', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['xml2', 'check', 'examples', 'perl'],
['xml2', 'check', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'perl'],
['xml2', 'check', 'examples', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['xml2', 'check', 'examples', 'python'],
['xml2', 'check', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'python'],
['xml2', 'check', 'examples', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'examples', 'python'],
['xml2', 'check', 'cpp_ns', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['xml2', 'check', 'examples', 'r'],
['xml2', 'check', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'r'],
['xml2', 'check', 'examples', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'examples', 'r'],
['xml2', 'check', 'cpp_ns', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['xml2', 'check', 'examples', 'ruby'],
['xml2', 'check', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'ruby'],
['xml2', 'check', 'examples', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'examples', 'ruby'],
['xml2', 'check', 'cpp_ns', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['expat', 'check', 'examples'],
['expat', 'check', 'strict'],
['expat', 'check', 'cpp_ns'],
['expat', 'check', 'examples', 'strict'],
['expat', 'check', 'cpp_ns', 'examples'],
['expat', 'check', 'cpp_ns', 'strict'],
['expat', 'check', 'cpp_ns', 'examples', 'strict'],
['expat', 'check', 'examples', 'csharp'],
['expat', 'check', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'csharp'],
['expat', 'check', 'examples', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['expat', 'check', 'examples', 'java'],
['expat', 'check', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'java'],
['expat', 'check', 'examples', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'examples', 'java'],
['expat', 'check', 'cpp_ns', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['expat', 'check', 'examples', 'perl'],
['expat', 'check', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'perl'],
['expat', 'check', 'examples', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'examples', 'perl'],
['expat', 'check', 'cpp_ns', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['expat', 'check', 'examples', 'python'],
['expat', 'check', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'python'],
['expat', 'check', 'examples', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'examples', 'python'],
['expat', 'check', 'cpp_ns', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['expat', 'check', 'examples', 'r'],
['expat', 'check', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'r'],
['expat', 'check', 'examples', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'examples', 'r'],
['expat', 'check', 'cpp_ns', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['expat', 'check', 'examples', 'ruby'],
['expat', 'check', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'ruby'],
['expat', 'check', 'examples', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'examples', 'ruby'],
['expat', 'check', 'cpp_ns', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['xerces', 'check', 'examples'],
['xerces', 'check', 'strict'],
['xerces', 'check', 'cpp_ns'],
['xerces', 'check', 'examples', 'strict'],
['xerces', 'check', 'cpp_ns', 'examples'],
['xerces', 'check', 'cpp_ns', 'strict'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['xerces', 'check', 'examples', 'csharp'],
['xerces', 'check', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'csharp'],
['xerces', 'check', 'examples', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['xerces', 'check', 'examples', 'java'],
['xerces', 'check', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'java'],
['xerces', 'check', 'examples', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'examples', 'java'],
['xerces', 'check', 'cpp_ns', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['xerces', 'check', 'examples', 'perl'],
['xerces', 'check', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'perl'],
['xerces', 'check', 'examples', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['xerces', 'check', 'examples', 'python'],
['xerces', 'check', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'python'],
['xerces', 'check', 'examples', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'examples', 'python'],
['xerces', 'check', 'cpp_ns', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['xerces', 'check', 'examples', 'r'],
['xerces', 'check', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'r'],
['xerces', 'check', 'examples', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'examples', 'r'],
['xerces', 'check', 'cpp_ns', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['xerces', 'check', 'examples', 'ruby'],
['xerces', 'check', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'ruby'],
['xerces', 'check', 'examples', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'examples', 'ruby'],
['xerces', 'check', 'cpp_ns', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]

all_with_packages = [\
['packages', 'xml2', 'check', 'examples'],
['packages', 'xml2', 'check', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns'],
['packages', 'xml2', 'check', 'examples', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'xml2', 'check', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'java'],
['packages', 'xml2', 'check', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'java'],
['packages', 'xml2', 'check', 'examples', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'xml2', 'check', 'examples', 'perl'],
['packages', 'xml2', 'check', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'perl'],
['packages', 'xml2', 'check', 'examples', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'xml2', 'check', 'examples', 'python'],
['packages', 'xml2', 'check', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'python'],
['packages', 'xml2', 'check', 'examples', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'xml2', 'check', 'examples', 'r'],
['packages', 'xml2', 'check', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'r'],
['packages', 'xml2', 'check', 'examples', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'xml2', 'check', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'ruby'],
['packages', 'xml2', 'check', 'examples', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['packages', 'expat', 'check', 'examples'],
['packages', 'expat', 'check', 'strict'],
['packages', 'expat', 'check', 'cpp_ns'],
['packages', 'expat', 'check', 'examples', 'strict'],
['packages', 'expat', 'check', 'cpp_ns', 'examples'],
['packages', 'expat', 'check', 'cpp_ns', 'strict'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'expat', 'check', 'examples', 'csharp'],
['packages', 'expat', 'check', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'csharp'],
['packages', 'expat', 'check', 'examples', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'expat', 'check', 'examples', 'java'],
['packages', 'expat', 'check', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'java'],
['packages', 'expat', 'check', 'examples', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'expat', 'check', 'examples', 'perl'],
['packages', 'expat', 'check', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'perl'],
['packages', 'expat', 'check', 'examples', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'expat', 'check', 'examples', 'python'],
['packages', 'expat', 'check', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'python'],
['packages', 'expat', 'check', 'examples', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'expat', 'check', 'examples', 'r'],
['packages', 'expat', 'check', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'r'],
['packages', 'expat', 'check', 'examples', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'expat', 'check', 'examples', 'ruby'],
['packages', 'expat', 'check', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'ruby'],
['packages', 'expat', 'check', 'examples', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'examples'],
['packages', 'xerces', 'check', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns'],
['packages', 'xerces', 'check', 'examples', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'xerces', 'check', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'java'],
['packages', 'xerces', 'check', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'java'],
['packages', 'xerces', 'check', 'examples', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'xerces', 'check', 'examples', 'perl'],
['packages', 'xerces', 'check', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['packages', 'xerces', 'check', 'examples', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'xerces', 'check', 'examples', 'python'],
['packages', 'xerces', 'check', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'python'],
['packages', 'xerces', 'check', 'examples', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'xerces', 'check', 'examples', 'r'],
['packages', 'xerces', 'check', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'r'],
['packages', 'xerces', 'check', 'examples', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'xerces', 'check', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'ruby'],
['packages', 'xerces', 'check', 'examples', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]

all_combinations = [\
['xml2', 'check', 'examples'],
['xml2', 'check', 'strict'],
['xml2', 'check', 'cpp_ns'],
['xml2', 'check', 'examples', 'strict'],
['xml2', 'check', 'cpp_ns', 'examples'],
['xml2', 'check', 'cpp_ns', 'strict'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['xml2', 'check', 'examples', 'csharp'],
['xml2', 'check', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'csharp'],
['xml2', 'check', 'examples', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['xml2', 'check', 'examples', 'java'],
['xml2', 'check', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'java'],
['xml2', 'check', 'examples', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'examples', 'java'],
['xml2', 'check', 'cpp_ns', 'strict', 'java'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['xml2', 'check', 'examples', 'perl'],
['xml2', 'check', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'perl'],
['xml2', 'check', 'examples', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['xml2', 'check', 'examples', 'python'],
['xml2', 'check', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'python'],
['xml2', 'check', 'examples', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'examples', 'python'],
['xml2', 'check', 'cpp_ns', 'strict', 'python'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['xml2', 'check', 'examples', 'r'],
['xml2', 'check', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'r'],
['xml2', 'check', 'examples', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'examples', 'r'],
['xml2', 'check', 'cpp_ns', 'strict', 'r'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['xml2', 'check', 'examples', 'ruby'],
['xml2', 'check', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'ruby'],
['xml2', 'check', 'examples', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'examples', 'ruby'],
['xml2', 'check', 'cpp_ns', 'strict', 'ruby'],
['xml2', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['expat', 'check', 'examples'],
['expat', 'check', 'strict'],
['expat', 'check', 'cpp_ns'],
['expat', 'check', 'examples', 'strict'],
['expat', 'check', 'cpp_ns', 'examples'],
['expat', 'check', 'cpp_ns', 'strict'],
['expat', 'check', 'cpp_ns', 'examples', 'strict'],
['expat', 'check', 'examples', 'csharp'],
['expat', 'check', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'csharp'],
['expat', 'check', 'examples', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['expat', 'check', 'examples', 'java'],
['expat', 'check', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'java'],
['expat', 'check', 'examples', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'examples', 'java'],
['expat', 'check', 'cpp_ns', 'strict', 'java'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['expat', 'check', 'examples', 'perl'],
['expat', 'check', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'perl'],
['expat', 'check', 'examples', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'examples', 'perl'],
['expat', 'check', 'cpp_ns', 'strict', 'perl'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['expat', 'check', 'examples', 'python'],
['expat', 'check', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'python'],
['expat', 'check', 'examples', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'examples', 'python'],
['expat', 'check', 'cpp_ns', 'strict', 'python'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['expat', 'check', 'examples', 'r'],
['expat', 'check', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'r'],
['expat', 'check', 'examples', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'examples', 'r'],
['expat', 'check', 'cpp_ns', 'strict', 'r'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['expat', 'check', 'examples', 'ruby'],
['expat', 'check', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'ruby'],
['expat', 'check', 'examples', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'examples', 'ruby'],
['expat', 'check', 'cpp_ns', 'strict', 'ruby'],
['expat', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['xerces', 'check', 'examples'],
['xerces', 'check', 'strict'],
['xerces', 'check', 'cpp_ns'],
['xerces', 'check', 'examples', 'strict'],
['xerces', 'check', 'cpp_ns', 'examples'],
['xerces', 'check', 'cpp_ns', 'strict'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['xerces', 'check', 'examples', 'csharp'],
['xerces', 'check', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'csharp'],
['xerces', 'check', 'examples', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['xerces', 'check', 'examples', 'java'],
['xerces', 'check', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'java'],
['xerces', 'check', 'examples', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'examples', 'java'],
['xerces', 'check', 'cpp_ns', 'strict', 'java'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['xerces', 'check', 'examples', 'perl'],
['xerces', 'check', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'perl'],
['xerces', 'check', 'examples', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['xerces', 'check', 'examples', 'python'],
['xerces', 'check', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'python'],
['xerces', 'check', 'examples', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'examples', 'python'],
['xerces', 'check', 'cpp_ns', 'strict', 'python'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['xerces', 'check', 'examples', 'r'],
['xerces', 'check', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'r'],
['xerces', 'check', 'examples', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'examples', 'r'],
['xerces', 'check', 'cpp_ns', 'strict', 'r'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['xerces', 'check', 'examples', 'ruby'],
['xerces', 'check', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'ruby'],
['xerces', 'check', 'examples', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'examples', 'ruby'],
['xerces', 'check', 'cpp_ns', 'strict', 'ruby'],
['xerces', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'examples'],
['packages', 'xml2', 'check', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns'],
['packages', 'xml2', 'check', 'examples', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'xml2', 'check', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'xml2', 'check', 'examples', 'java'],
['packages', 'xml2', 'check', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'java'],
['packages', 'xml2', 'check', 'examples', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'xml2', 'check', 'examples', 'perl'],
['packages', 'xml2', 'check', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'perl'],
['packages', 'xml2', 'check', 'examples', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'xml2', 'check', 'examples', 'python'],
['packages', 'xml2', 'check', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'python'],
['packages', 'xml2', 'check', 'examples', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'xml2', 'check', 'examples', 'r'],
['packages', 'xml2', 'check', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'r'],
['packages', 'xml2', 'check', 'examples', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'xml2', 'check', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'ruby'],
['packages', 'xml2', 'check', 'examples', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['packages', 'expat', 'check', 'examples'],
['packages', 'expat', 'check', 'strict'],
['packages', 'expat', 'check', 'cpp_ns'],
['packages', 'expat', 'check', 'examples', 'strict'],
['packages', 'expat', 'check', 'cpp_ns', 'examples'],
['packages', 'expat', 'check', 'cpp_ns', 'strict'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'expat', 'check', 'examples', 'csharp'],
['packages', 'expat', 'check', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'csharp'],
['packages', 'expat', 'check', 'examples', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'expat', 'check', 'examples', 'java'],
['packages', 'expat', 'check', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'java'],
['packages', 'expat', 'check', 'examples', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'expat', 'check', 'examples', 'perl'],
['packages', 'expat', 'check', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'perl'],
['packages', 'expat', 'check', 'examples', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'expat', 'check', 'examples', 'python'],
['packages', 'expat', 'check', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'python'],
['packages', 'expat', 'check', 'examples', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'expat', 'check', 'examples', 'r'],
['packages', 'expat', 'check', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'r'],
['packages', 'expat', 'check', 'examples', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'expat', 'check', 'examples', 'ruby'],
['packages', 'expat', 'check', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'ruby'],
['packages', 'expat', 'check', 'examples', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'examples'],
['packages', 'xerces', 'check', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns'],
['packages', 'xerces', 'check', 'examples', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['packages', 'xerces', 'check', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['packages', 'xerces', 'check', 'examples', 'java'],
['packages', 'xerces', 'check', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'java'],
['packages', 'xerces', 'check', 'examples', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['packages', 'xerces', 'check', 'examples', 'perl'],
['packages', 'xerces', 'check', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['packages', 'xerces', 'check', 'examples', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['packages', 'xerces', 'check', 'examples', 'python'],
['packages', 'xerces', 'check', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'python'],
['packages', 'xerces', 'check', 'examples', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['packages', 'xerces', 'check', 'examples', 'r'],
['packages', 'xerces', 'check', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'r'],
['packages', 'xerces', 'check', 'examples', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['packages', 'xerces', 'check', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'ruby'],
['packages', 'xerces', 'check', 'examples', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'strict', 'ruby'],
['packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'ruby']]


