all_combinations = [\
['base', 'xml2', 'check', 'examples'],
['base', 'xml2', 'check', 'strict'],
['base', 'xml2', 'check', 'cpp_ns'],
['base', 'xml2', 'check', 'examples', 'strict'],
['base', 'xml2', 'check', 'cpp_ns', 'examples'],
['base', 'xml2', 'check', 'cpp_ns', 'strict'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'xml2', 'check', 'examples', 'csharp'],
['base', 'xml2', 'check', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'csharp'],
['base', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'xml2', 'check', 'examples', 'java'],
['base', 'xml2', 'check', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'java'],
['base', 'xml2', 'check', 'examples', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'xml2', 'check', 'examples', 'perl'],
['base', 'xml2', 'check', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'perl'],
['base', 'xml2', 'check', 'examples', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'xml2', 'check', 'examples', 'python'],
['base', 'xml2', 'check', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'python'],
['base', 'xml2', 'check', 'examples', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'xml2', 'check', 'examples', 'r'],
['base', 'xml2', 'check', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'r'],
['base', 'xml2', 'check', 'examples', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'expat', 'check', 'examples'],
['base', 'expat', 'check', 'strict'],
['base', 'expat', 'check', 'cpp_ns'],
['base', 'expat', 'check', 'examples', 'strict'],
['base', 'expat', 'check', 'cpp_ns', 'examples'],
['base', 'expat', 'check', 'cpp_ns', 'strict'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'expat', 'check', 'examples', 'csharp'],
['base', 'expat', 'check', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'csharp'],
['base', 'expat', 'check', 'examples', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'expat', 'check', 'examples', 'java'],
['base', 'expat', 'check', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'java'],
['base', 'expat', 'check', 'examples', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'expat', 'check', 'examples', 'perl'],
['base', 'expat', 'check', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'perl'],
['base', 'expat', 'check', 'examples', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'expat', 'check', 'examples', 'python'],
['base', 'expat', 'check', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'python'],
['base', 'expat', 'check', 'examples', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'expat', 'check', 'examples', 'r'],
['base', 'expat', 'check', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'r'],
['base', 'expat', 'check', 'examples', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'xerces', 'check', 'examples'],
['base', 'xerces', 'check', 'strict'],
['base', 'xerces', 'check', 'cpp_ns'],
['base', 'xerces', 'check', 'examples', 'strict'],
['base', 'xerces', 'check', 'cpp_ns', 'examples'],
['base', 'xerces', 'check', 'cpp_ns', 'strict'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'xerces', 'check', 'examples', 'csharp'],
['base', 'xerces', 'check', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'csharp'],
['base', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'xerces', 'check', 'examples', 'java'],
['base', 'xerces', 'check', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'java'],
['base', 'xerces', 'check', 'examples', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'xerces', 'check', 'examples', 'perl'],
['base', 'xerces', 'check', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'perl'],
['base', 'xerces', 'check', 'examples', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'xerces', 'check', 'examples', 'python'],
['base', 'xerces', 'check', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'python'],
['base', 'xerces', 'check', 'examples', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'xerces', 'check', 'examples', 'r'],
['base', 'xerces', 'check', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'r'],
['base', 'xerces', 'check', 'examples', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'examples'],
['base', 'packages', 'xml2', 'check', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'xml2', 'check', 'examples', 'csharp'],
['base', 'packages', 'xml2', 'check', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'examples', 'java'],
['base', 'packages', 'xml2', 'check', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'examples', 'perl'],
['base', 'packages', 'xml2', 'check', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'examples', 'python'],
['base', 'packages', 'xml2', 'check', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'examples', 'r'],
['base', 'packages', 'xml2', 'check', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'examples'],
['base', 'packages', 'expat', 'check', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns'],
['base', 'packages', 'expat', 'check', 'examples', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'expat', 'check', 'examples', 'csharp'],
['base', 'packages', 'expat', 'check', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'examples', 'java'],
['base', 'packages', 'expat', 'check', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'examples', 'perl'],
['base', 'packages', 'expat', 'check', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'examples', 'python'],
['base', 'packages', 'expat', 'check', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'examples', 'r'],
['base', 'packages', 'expat', 'check', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'examples'],
['base', 'packages', 'xerces', 'check', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'xerces', 'check', 'examples', 'csharp'],
['base', 'packages', 'xerces', 'check', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'examples', 'java'],
['base', 'packages', 'xerces', 'check', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'examples', 'perl'],
['base', 'packages', 'xerces', 'check', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'examples', 'python'],
['base', 'packages', 'xerces', 'check', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'examples', 'r'],
['base', 'packages', 'xerces', 'check', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r']]

all_no_packages = [\
['base', 'xml2', 'check', 'examples'],
['base', 'xml2', 'check', 'strict'],
['base', 'xml2', 'check', 'cpp_ns'],
['base', 'xml2', 'check', 'examples', 'strict'],
['base', 'xml2', 'check', 'cpp_ns', 'examples'],
['base', 'xml2', 'check', 'cpp_ns', 'strict'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'xml2', 'check', 'examples', 'csharp'],
['base', 'xml2', 'check', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'csharp'],
['base', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'xml2', 'check', 'examples', 'java'],
['base', 'xml2', 'check', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'java'],
['base', 'xml2', 'check', 'examples', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'xml2', 'check', 'examples', 'perl'],
['base', 'xml2', 'check', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'perl'],
['base', 'xml2', 'check', 'examples', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'xml2', 'check', 'examples', 'python'],
['base', 'xml2', 'check', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'python'],
['base', 'xml2', 'check', 'examples', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'xml2', 'check', 'examples', 'r'],
['base', 'xml2', 'check', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'r'],
['base', 'xml2', 'check', 'examples', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'expat', 'check', 'examples'],
['base', 'expat', 'check', 'strict'],
['base', 'expat', 'check', 'cpp_ns'],
['base', 'expat', 'check', 'examples', 'strict'],
['base', 'expat', 'check', 'cpp_ns', 'examples'],
['base', 'expat', 'check', 'cpp_ns', 'strict'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'expat', 'check', 'examples', 'csharp'],
['base', 'expat', 'check', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'csharp'],
['base', 'expat', 'check', 'examples', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'expat', 'check', 'examples', 'java'],
['base', 'expat', 'check', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'java'],
['base', 'expat', 'check', 'examples', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'expat', 'check', 'examples', 'perl'],
['base', 'expat', 'check', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'perl'],
['base', 'expat', 'check', 'examples', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'expat', 'check', 'examples', 'python'],
['base', 'expat', 'check', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'python'],
['base', 'expat', 'check', 'examples', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'expat', 'check', 'examples', 'r'],
['base', 'expat', 'check', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'r'],
['base', 'expat', 'check', 'examples', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'xerces', 'check', 'examples'],
['base', 'xerces', 'check', 'strict'],
['base', 'xerces', 'check', 'cpp_ns'],
['base', 'xerces', 'check', 'examples', 'strict'],
['base', 'xerces', 'check', 'cpp_ns', 'examples'],
['base', 'xerces', 'check', 'cpp_ns', 'strict'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'xerces', 'check', 'examples', 'csharp'],
['base', 'xerces', 'check', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'csharp'],
['base', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'xerces', 'check', 'examples', 'java'],
['base', 'xerces', 'check', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'java'],
['base', 'xerces', 'check', 'examples', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'xerces', 'check', 'examples', 'perl'],
['base', 'xerces', 'check', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'perl'],
['base', 'xerces', 'check', 'examples', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'xerces', 'check', 'examples', 'python'],
['base', 'xerces', 'check', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'python'],
['base', 'xerces', 'check', 'examples', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'xerces', 'check', 'examples', 'r'],
['base', 'xerces', 'check', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'r'],
['base', 'xerces', 'check', 'examples', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r']]

all_with_packages = [\
['base', 'packages', 'xml2', 'check', 'examples'],
['base', 'packages', 'xml2', 'check', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'xml2', 'check', 'examples', 'csharp'],
['base', 'packages', 'xml2', 'check', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'examples', 'java'],
['base', 'packages', 'xml2', 'check', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'examples', 'perl'],
['base', 'packages', 'xml2', 'check', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'examples', 'python'],
['base', 'packages', 'xml2', 'check', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'examples', 'r'],
['base', 'packages', 'xml2', 'check', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'examples'],
['base', 'packages', 'expat', 'check', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns'],
['base', 'packages', 'expat', 'check', 'examples', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'expat', 'check', 'examples', 'csharp'],
['base', 'packages', 'expat', 'check', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'examples', 'java'],
['base', 'packages', 'expat', 'check', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'examples', 'perl'],
['base', 'packages', 'expat', 'check', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'examples', 'python'],
['base', 'packages', 'expat', 'check', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'examples', 'r'],
['base', 'packages', 'expat', 'check', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'examples'],
['base', 'packages', 'xerces', 'check', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'xerces', 'check', 'examples', 'csharp'],
['base', 'packages', 'xerces', 'check', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'examples', 'java'],
['base', 'packages', 'xerces', 'check', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'examples', 'perl'],
['base', 'packages', 'xerces', 'check', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'examples', 'python'],
['base', 'packages', 'xerces', 'check', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'examples', 'r'],
['base', 'packages', 'xerces', 'check', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r']]

all_xml2 = [\
['base', 'xml2', 'check', 'examples'],
['base', 'xml2', 'check', 'strict'],
['base', 'xml2', 'check', 'cpp_ns'],
['base', 'xml2', 'check', 'examples', 'strict'],
['base', 'xml2', 'check', 'cpp_ns', 'examples'],
['base', 'xml2', 'check', 'cpp_ns', 'strict'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'xml2', 'check', 'examples', 'csharp'],
['base', 'xml2', 'check', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'csharp'],
['base', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'xml2', 'check', 'examples', 'java'],
['base', 'xml2', 'check', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'java'],
['base', 'xml2', 'check', 'examples', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'xml2', 'check', 'examples', 'perl'],
['base', 'xml2', 'check', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'perl'],
['base', 'xml2', 'check', 'examples', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'xml2', 'check', 'examples', 'python'],
['base', 'xml2', 'check', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'python'],
['base', 'xml2', 'check', 'examples', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'xml2', 'check', 'examples', 'r'],
['base', 'xml2', 'check', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'r'],
['base', 'xml2', 'check', 'examples', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'examples'],
['base', 'packages', 'xml2', 'check', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'xml2', 'check', 'examples', 'csharp'],
['base', 'packages', 'xml2', 'check', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xml2', 'check', 'examples', 'java'],
['base', 'packages', 'xml2', 'check', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'xml2', 'check', 'examples', 'perl'],
['base', 'packages', 'xml2', 'check', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'xml2', 'check', 'examples', 'python'],
['base', 'packages', 'xml2', 'check', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'xml2', 'check', 'examples', 'r'],
['base', 'packages', 'xml2', 'check', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'xml2', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'xml2', 'check', 'cpp_ns', 'examples', 'strict', 'r']]

all_expat = [\
['base', 'expat', 'check', 'examples'],
['base', 'expat', 'check', 'strict'],
['base', 'expat', 'check', 'cpp_ns'],
['base', 'expat', 'check', 'examples', 'strict'],
['base', 'expat', 'check', 'cpp_ns', 'examples'],
['base', 'expat', 'check', 'cpp_ns', 'strict'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'expat', 'check', 'examples', 'csharp'],
['base', 'expat', 'check', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'csharp'],
['base', 'expat', 'check', 'examples', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'expat', 'check', 'examples', 'java'],
['base', 'expat', 'check', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'java'],
['base', 'expat', 'check', 'examples', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'expat', 'check', 'examples', 'perl'],
['base', 'expat', 'check', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'perl'],
['base', 'expat', 'check', 'examples', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'expat', 'check', 'examples', 'python'],
['base', 'expat', 'check', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'python'],
['base', 'expat', 'check', 'examples', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'expat', 'check', 'examples', 'r'],
['base', 'expat', 'check', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'r'],
['base', 'expat', 'check', 'examples', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'examples'],
['base', 'packages', 'expat', 'check', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns'],
['base', 'packages', 'expat', 'check', 'examples', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'expat', 'check', 'examples', 'csharp'],
['base', 'packages', 'expat', 'check', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'expat', 'check', 'examples', 'java'],
['base', 'packages', 'expat', 'check', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'expat', 'check', 'examples', 'perl'],
['base', 'packages', 'expat', 'check', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'expat', 'check', 'examples', 'python'],
['base', 'packages', 'expat', 'check', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'expat', 'check', 'examples', 'r'],
['base', 'packages', 'expat', 'check', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'expat', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'expat', 'check', 'cpp_ns', 'examples', 'strict', 'r']]

all_xerces = [\
['base', 'xerces', 'check', 'examples'],
['base', 'xerces', 'check', 'strict'],
['base', 'xerces', 'check', 'cpp_ns'],
['base', 'xerces', 'check', 'examples', 'strict'],
['base', 'xerces', 'check', 'cpp_ns', 'examples'],
['base', 'xerces', 'check', 'cpp_ns', 'strict'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'xerces', 'check', 'examples', 'csharp'],
['base', 'xerces', 'check', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'csharp'],
['base', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'xerces', 'check', 'examples', 'java'],
['base', 'xerces', 'check', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'java'],
['base', 'xerces', 'check', 'examples', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'xerces', 'check', 'examples', 'perl'],
['base', 'xerces', 'check', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'perl'],
['base', 'xerces', 'check', 'examples', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'xerces', 'check', 'examples', 'python'],
['base', 'xerces', 'check', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'python'],
['base', 'xerces', 'check', 'examples', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'xerces', 'check', 'examples', 'r'],
['base', 'xerces', 'check', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'r'],
['base', 'xerces', 'check', 'examples', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'examples'],
['base', 'packages', 'xerces', 'check', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict'],
['base', 'packages', 'xerces', 'check', 'examples', 'csharp'],
['base', 'packages', 'xerces', 'check', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'csharp'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'csharp'],
['base', 'packages', 'xerces', 'check', 'examples', 'java'],
['base', 'packages', 'xerces', 'check', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'java'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'java'],
['base', 'packages', 'xerces', 'check', 'examples', 'perl'],
['base', 'packages', 'xerces', 'check', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'perl'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'perl'],
['base', 'packages', 'xerces', 'check', 'examples', 'python'],
['base', 'packages', 'xerces', 'check', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'python'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'python'],
['base', 'packages', 'xerces', 'check', 'examples', 'r'],
['base', 'packages', 'xerces', 'check', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'r'],
['base', 'packages', 'xerces', 'check', 'examples', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'strict', 'r'],
['base', 'packages', 'xerces', 'check', 'cpp_ns', 'examples', 'strict', 'r']]

















